In [1]:
# Week 2 Task 1
f = open("Numbers.txt", "w")
f.write("3\n")
f.write("45\n")
f.write("83\n")
f.close()

f = open("Numbers.txt", "r")
print(f.read())

f = open("Numbers.txt", "a")
f.write("21\n")

f = open("Numbers.txt", "r")
print(f.read())

3
45
83

3
45
83
21



In [20]:
def mark_grade(mark, target_grade):
    
    if mark <= 49:
        exam_grade = "D"
    elif mark <= 59:
        exam_grade = "c"
    elif mark <= 69:
        exam_grade = "B"
    else:
        exam_grade = "A"
    return exam_grade


mark = input("Enter your percentage mark: ")
mark = int(mark)
target_grade = input("Enter your target grade: ")
exam_grade = mark_grade(mark, target_grade)
if target_grade == exam_grade:
    print(f"Your grade is {exam_grade} based on your marks, so you have scored the expected grade")
elif target_grade < exam_grade:
    print(f"Your grade is {exam_grade} based on your marks, so you have scored less than your expected grade ({target_grade})")
else:
    print(f"Your grade is {exam_grade} based on your marks, so you have scored more than your expected grade ({target_grade})")


Your grade is D based on your marks, so you have scored less than your expected grade (A)


In [21]:
# Week 2 Home Learning Project
import numpy as np

# 1. Create a 1D array of numbers from 0 to 9
num_array = np.arange(10)
print("QUESTION 1 : 1D array from 0 to 9: ", num_array)

# 2. Create a 3×3 NumPy array of all Boolean value Trues
num_array_boolean = np.array([1,1,1,1,1,1,1,1,1]).reshape(3,3)
print("QUESTION 2 : 3x3 NumPy array of Boolean value Trues \n",num_array_boolean)

# 3. Extract all odd numbers from array of 1-10
all_numbers = np.arange(1,11,1)
print("All numbers in range 1 to 10: ",all_numbers)
odd_numbers = all_numbers[all_numbers % 2 == 1]
print("QUESTION 3 : Odd numbers in array 1 to 10:\n", odd_numbers)

# 4. Replace all odd numbers in an array of 1-10 with the value -1
all_numbers1 = np.arange(1,11,1)
odd_num_replace = np.where(all_numbers1 % 2 ==1, -1, all_numbers1)
print("QUESTION 4 : Odd number replace with -1: \n",odd_num_replace)

# 5. Convert a 1D array to a 2D array with 2 rows
two_d_array = np.arange(1,5)
two_d_array = two_d_array.reshape(2,2)
print("QUESTION 5: 1D array to 2D array\n",two_d_array)

# 6. Create two arrays a and b, stack these two arrays vertically use the np.dot and
# np.sum to calculate totals
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
multiply = np.dot(a, b)
print("QUESTION 6: Multiplation of 2 arrays:\n",multiply)
sum = np.sum(multiply,axis =0)
print("Sum: ",sum)


QUESTION 1 : 1D array from 0 to 9:  [0 1 2 3 4 5 6 7 8 9]
QUESTION 2 : 3x3 NumPy array of Boolean value Trues 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
All numbers in range 1 to 10:  [ 1  2  3  4  5  6  7  8  9 10]
QUESTION 3 : Odd numbers in array 1 to 10:
 [1 3 5 7 9]
QUESTION 4 : Odd number replace with -1: 
 [-1  2 -1  4 -1  6 -1  8 -1 10]
QUESTION 5: 1D array to 2D array
 [[1 2]
 [3 4]]
QUESTION 6: Multiplation of 2 arrays:
 [[19 22]
 [43 50]]
Sum:  [62 72]


In [22]:
# Week 2 Home Learning project EXTENSION 
# Task 1
import numpy as np

arr_1 = np.full((1,3), 1)
arr_2 = np.full((1,3),2)
arr_3 = np.full((1,3),3)
arr = np.arange(1,4,1)

final = np.concatenate((arr_1,arr_2),axis=1)
final = np.concatenate((final,arr_3),axis=1)
final = final.flatten()
#print(final)
final1 = np.concatenate((arr,arr))
final1 = np.concatenate((arr,final1))
final_list = np.concatenate((final,final1))

print("Final output\n",final_list)

Final output
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [23]:
# Week 2 Home Learning project EXTENSION 
# Task 2
import numpy as np
A = np.array([1,2,3,4,5])
print("List a:\n",A)
B = np.array([4,5,6,7,8,9])
print("List b:\n",B)

C = np.array(list(filter(lambda x: x not in A,B)))
print("List of b after removing duplicates from a: \n",C)
updated_a = A[A > 3]
print(updated_a)
updated_b = B[B < 7]
print(updated_b)
add_array1 = np.sum(updated_a, axis=0)
add_array2 = np.sum(updated_b, axis=0)
final = add_array1 + add_array2
print("Sum of items between 3 and 7 in array a and b: ",final)

List a:
 [1 2 3 4 5]
List b:
 [4 5 6 7 8 9]
List of b after removing duplicates from a: 
 [6 7 8 9]
[4 5]
[4 5 6]
Sum of items between 3 and 7 in array a and b:  24
